fix(services): Enable vault in production
adfinis-sygroup/customer-center pull request #136
Opened 2020-09-15 13:12 UTC by aziiee

2020-09-15 13:13 UTC, fkm approved these changes

2020-09-15 13:20 UTC, fkm-adfinis approved these changes

2020-09-16 08:54 UTC, fkm-adfinis requested changes

2020-09-16 08:54 UTC, fkm-adfinis commented on Makefile
>  	echo "Vault integration is disabled."
This line doesn't apply any more.

2020-09-16 09:00 UTC, aziiee commented on Makefile
>  	echo "Vault integration is disabled."
fixed

2020-09-16 09:04 UTC, fkm-adfinis approved these changes

2020-09-16 09:15 UTC, merged