feat(frontend): add new Adfinis locations to dashboard
adfinis-sygroup/customer-center pull request #153
Opened 2020-10-27 15:18 UTC by fkm-adfinis

Depends on #152 

Because the old list was... old.

2020-11-02 14:08 UTC, velrest requested changes

2020-11-02 14:08 UTC, velrest commented on frontend/app/ui/index/route.js
> +            title: "Adfinis AG",
```suggestion
            title: "Adfinis NL",
```

2020-11-05 09:31 UTC, fkm-adfinis commented on frontend/app/ui/index/route.js
> +            title: "Adfinis AG",
Thank you! :sunglasses:

2020-11-06 08:17 UTC, velrest approved these changes

2020-11-18 08:43 UTC, merged